---
title: "MSE_analysis_HCR4"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r initial_setup}

library(tidyr)
library(dplyr)
library(ggplot2)

# Specify path of parent directory
pdir = "D:/OneDrive - IATTC/IATTC/2025/MSE/Test/"

# Specify the path of conditioned initial OM
sdir = "D:/OneDrive - IATTC/IATTC/2025/SAC16/BET F30/"

# Dimensions
library(IATTCMSE)
library(foreach)
library(doParallel)

#Specify path of parent directory
pdir <- "D:/OneDrive - IATTC/IATTC/2025/MSE/Test/"

#Specify the path of conditioned initial OM
sdir <- "D:/OneDrive - IATTC/IATTC/2025/SAC16/BET F30/"

# Dimensions
niterations <- 3
nyears <- 30
nquarters <- nyears * 4
Mcycle <- 3
nsteps <- nyears / Mcycle
endquarter <- 196
startquarter <- 17
n_extra_R <- 2 #number of assessment period recruitment in the projection

OM_name <- c("Fix-1-1", "Sel-1-1", "Gro-1-1", "Mrt-1-1")[1:4]
HCR_name <-  "HCR_staff_Fscaler"

# Set the harvest strategy
HSnum <- 1
HS <- paste0("HS", HSnum, "/")

# Set the HCR
HCR <- paste0(HCR_name, "/")
```

```{r management_output}
for (OMnum in 1:length(OM_name)) {
  # Set the scenario
  OM <- paste0(OM_name[OMnum], "/")
  
  # extract saved management output
  for (itrnum in 1:niterations) {
    itr = paste0("itr", itrnum, "/")
    
    skip_to_next <- FALSE
    
    tryCatch({
      Record <- read.csv(paste0(paste0(pdir, HS, HCR, OM, itr, "Record.csv")))
      Record$Step <- 1:nsteps
      Record$OM <- OM
      Record$itr <- itrnum
      
      if (OMnum == 1 & itrnum == 1)
        Record_all <- Record
      else
        Record_all <- rbind(Record_all, Record)
    }, error = function(e) {
      skip_to_next <<- TRUE
    })
    if (skip_to_next) {
      next
    }
  }
}


Record_all_count <- Record_all %>%
  filter(Step == nsteps, max_gradient < 0.05) %>%
  group_by(OM) %>%
  summarise(count = n())

Record_all_failed <- Record_all %>%
  filter(Step == nsteps) %>%
  filter(max_gradient > 0.05 | is.na(max_gradient)) %>%
  select(OM, itr) %>%
  mutate(Flag = 0)

Record_all_run <- Record_all
Record_all_passed <- left_join(Record_all, Record_all_failed) %>%
  filter(is.na(Flag))
  
Record_all$itr <- as.factor(Record_all$itr)
Record_all$Step <- as.factor(Record_all$Step)

ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = closure, fill = OM)) +
  theme_bw()
  
ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = SBR_d, fill = OM)) +
  theme_bw()

ggplot(data = Record_all_run) +
  geom_point(aes(x = Step, y = SBR_d, color = OM)) +
  theme_bw()
 
ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = Fadjust, fill = OM)) +
  theme_bw() +
  ylab("F/F30%")

# ggplot(data = Record_all) +
#   geom_boxplot(aes(x = Step, y = (Time_Stamp - min(Time_Stamp))/60, fill = OM)) +
#   theme_bw() +
#   ylab("Time chart in minute")
```

```{r fig.height=10, fig.width=20}
for (OMnum in 1:length(OM_name)) {
  # Set the scenario
  OM <- paste0(OM_name[OMnum], "/")
  
  for (itrnum in 1:niterations) {
    itr = paste0("itr", itrnum, "/")
    
    skip_to_next <- FALSE
    
    tryCatch({
      Output <- read.csv(paste0(paste0(pdir, HS, HCR, OM, itr, "Output.csv")))
      Output$OM <- OM
      Output$itr <- itrnum
      
      if (OMnum == 1 & itrnum == 1)
        Output_all <- Output
      else
        Output_all <- rbind(Output_all, Output)
    }, error = function(e) {
      skip_to_next <<- TRUE
    })
    if (skip_to_next) {
      next
    }
  }
}

Output_all_long <- Output_all %>%
  mutate(itr = as.factor(itr),
         Year = Year / 4 + 1974.875,
         year = floor(Year) + 0.5) %>%
  gather(2:7, key = "Quantity", value = "Value") %>%
  filter(Quantity %in% c("Catch", "SB", "SBR", "SBR_d"))

output_all_old <- Output_all_long %>%
  filter(Year < 2024)
output_all_new <- Output_all_long %>%
  filter(Year > 2024, Year < max(Year))

# SB_all <- output_all_old %>% filter(Quantity == "SBR_d", itr == 1, (Year-floor(Year)) == 0.125)
# SB_all_mean <- SB_all %>%
  # group_by(Year) %>%
  # summarise(Value = mean(Value))

# ggplot() +
#   geom_point(aes(x = Year, y = Value, color = OM), alpha = 1, data = SB_all) +
#   geom_line(aes(x = Year, y = Value, color = OM), alpha = 1, data = SB_all) +
#   geom_point(aes(x = Year, y = Value), alpha = 1, data = SB_all_mean) +
#   geom_line(aes(x = Year, y = Value), alpha = 1, data = SB_all_mean) +
#   geom_hline(yintercept = 0.2) +
#   geom_hline(yintercept = 0.3) +
#   theme_bw() +
#   ylab("SBR_d")

ggplot() +
  geom_boxplot(aes(x = factor(year), y = Value, fill = OM), data = output_all_new) +
  facet_wrap(~Quantity, scales = "free_y", nrow = 2) +
  theme_bw()

ggplot() +
  geom_point(aes(x = Year, y = Value, color = OM, shape = OM), data = output_all_new) +
  facet_wrap(~Quantity, scales = "free_y", nrow = 2) +
  theme_bw()
```

```{r fig.height=10, fig.width=10}
# compare estimated and true SBR_d
Record_all$Year <- as.numeric(Record_all$Step) * Mcycle + 2021.125

# ggplot() +
#   geom_boxplot(aes(x = as.factor(Year), y = Value, fill = OM), data = output_all_new %>% filter(Quantity == "SBR_d", Year %in% Record_all$Year)) +
#   geom_boxplot(aes(x = as.factor(Year), y = SBR_d, fill = OM), data = Record_all) +
#   ylab("SBR_d") +
#   geom_hline(yintercept = 0.2) +
#   geom_hline(yintercept = 0.3, linetype = "dashed") +
#   facet_wrap(~OM, nrow = 4) +
#   theme_bw()
# 
# # compare estimated and true SB
# ggplot() +
#   geom_boxplot(aes(x = as.factor(Year), y = Value, fill = OM), data = output_all_new %>% filter(Quantity == "SB", Year %in% Record_all$Year)) +
#   geom_boxplot(aes(x = as.factor(Year), y = SB, fill = OM), data = Record_all) +
#   ylab("SB") +
#   facet_wrap(~OM, nrow = 4, scales = "free_y") +
#   theme_bw()

# compare SB ratio
Record_all_2 <- left_join(Record_all, output_all_new) %>%
  filter(Quantity == "SB") %>%
  mutate(SB_ratio = Value / SB)
ggplot() +
  geom_boxplot(aes(x = as.factor(Year), y = SB_ratio, fill = OM), data = Record_all_2) +
  ylab("SB_OM / SB_EM") +
  facet_wrap(~OM, nrow = 4) +
  theme_bw()

# compare SBR_d ratio
Record_all_2 <- left_join(Record_all, output_all_new) %>%
  filter(Quantity == "SBR_d") %>%
  mutate(SBR_d_ratio = Value / SBR_d)

ggplot() +
  geom_boxplot(aes(x = as.factor(Year), y = SBR_d_ratio, fill = OM), data = Record_all_2) +
  ylab("SBR_d_OM / SBR_d_EM") +
  facet_wrap(~OM, nrow = 4) +
  theme_bw()
```