---
title: "MSE_analysis_all"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      fig.height = 6, fig.width = 12)
```

```{r initial_setup}
library(tidyr)
library(dplyr)
library(ggplot2)
library(knitr)

#Specify path of parent directory
pdir <- "D:/OneDrive - IATTC/IATTC/2025/MSE/Test/"

#Specify the path of conditioned initial OM
sdir <- "D:/OneDrive - IATTC/IATTC/2025/SAC16/BET F30/"

# Dimensions
niterations <- 10
nyears <- 12
Mcycle <- 3
nsteps <- nyears / Mcycle

model = c("Fix", "Gro", "Sel", "Mrt")
catchability = c(1, 1.01, 1.02)
steepness = c(1, 0.9, 0.8)
converge <- array(1, dim = c(length(model), length(catchability), length(steepness)))
# converge[1, 3, 3] <- 0
# converge[4, 2, 2:3] <- 0

OM_list <- data.frame(expand.grid(
  model = model,
  catchability = catchability,
  steepness = steepness
))
OM_list$converge <- converge[1:36]
OM_list <- OM_list %>% filter(converge == 1)
OM_name <- paste0(OM_list$model, "-", OM_list$catchability, "-", OM_list$steepness)

Check_list <- data.frame(
  HSnum = c(1,1),
  HCR_name = c("HCR_staff","HCR_staff_Fscaler"),
  HS_plot = c("HS_Fix","HS_Fix_tuned"),
  HCR_plot = c("HCR_staff","HCR_staff")
)
```

```{r management_output}
for (i in 1:nrow(Check_list)) {
  # Set the HCR
  HCR <- paste0(Check_list$HCR_name[i], "/")
  HS <- paste0("HS", Check_list$HSnum[i], "/")
  
  for (OMnum in 1:length(OM_name)) {
    # Set the scenario
    OM <- paste0(OM_name[OMnum], "/")
    
    # extract saved management output
    for (itrnum in 1:niterations) {
      itr = paste0("itr", itrnum, "/")
      
      skip_to_next <- FALSE
      
      tryCatch({
        Record <- read.csv(paste0(paste0(
          pdir, HS, HCR, OM, itr, "Record.csv"
        )))
        Record$Step <- 1:nrow(Record)
        Record$OM <- OM_name[OMnum]
        Record$itr <- itrnum
        Record$HCR <- Check_list$HCR_plot[i]
        Record$HS <- Check_list$HS_plot[i]
        Record$Model <- stringr::str_split(OM_name[OMnum], "-",  simplify = TRUE)[1]
        Record$Catchability <- stringr::str_split(OM_name[OMnum], "-",  simplify = TRUE)[2]
        Record$Steepness <- stringr::str_split(OM_name[OMnum], "-",  simplify = TRUE)[3]
        
        if (i == 1 & OMnum == 1 & itrnum == 1)
          Record_all <- Record
        else
          Record_all <- rbind(Record_all, Record)
      }, error = function(e) {
        skip_to_next <<- TRUE
      })
      if (skip_to_next) {
        next
      }
    }
  }
}

Record_all_count <- Record_all %>%
  filter(Step == nsteps, max_gradient < 0.1) %>%
  group_by(HS, HCR, OM) %>%
  summarise(count = n())
kable(Record_all_count,caption = "Record_all_count")

Record_all_failed <- Record_all %>%
  filter(Step == nsteps) %>%
  filter(max_gradient > 0.1 | is.na(max_gradient)) %>%
  select(OM, itr) %>%
  mutate(Flag = 0)
kable(Record_all_failed,caption = "Record_all_failed")

Record_all <- left_join(Record_all, Record_all_failed) %>%
  filter(is.na(Flag))
  
Record_all$itr <- as.factor(Record_all$itr)
Record_all$Step <- as.factor(Record_all$Step)
Record_all$HCR <- as.factor(Record_all$HCR)
```

```{r fig.height=10, fig.width=10}
for (i in 1:nrow(Check_list)) {
  # Set the HCR
  HCR <- paste0(Check_list$HCR_name[i], "/")
  HS <- paste0("HS", Check_list$HSnum[i], "/")
  
  for (OMnum in 1:length(OM_name)) {
    # Set the scenario
    OM <- paste0(OM_name[OMnum], "/")
    
    for (itrnum in 1:niterations) {
      itr = paste0("itr", itrnum, "/")
      
      skip_to_next <- FALSE
      
      tryCatch({
        Output <- read.csv(paste0(paste0(pdir, HS, HCR, OM, itr, "Output.csv")))
        Output$OM <- OM_name[OMnum]
        Output$itr <- itrnum
        Output$HCR <- Check_list$HCR_plot[i]
        Output$HS <- Check_list$HS_plot[i]
        Output$Model <- strsplit(OM_name[OMnum], "-")[[1]][1]
        Output$Catchability <- strsplit(OM_name[OMnum], "-")[[1]][2]
        Output$Steepness <- strsplit(OM_name[OMnum], "-")[[1]][3]
        
        if (i == 1 & OMnum == 1 & itrnum == 1)
          Output_all <- Output
        else
          Output_all <- rbind(Output_all, Output)
      }, error = function(e) {
        skip_to_next <<- TRUE
      })
      if (skip_to_next) {
        next
      }
    }
  }
}

Output_all <- Output_all %>%
  mutate(itr = as.factor(itr),
         Year = Year / 4 + 1974.875,
         year = floor(Year) + 0.5)
Output_MSE <- Output_all %>% filter(year > 2025)
```

```{r SBR_d}
ggplot(data = Output_MSE) +
  geom_point(aes(x = Year, y = SBR_d, color = Model), alpha = 0.5, size = 1) +
  facet_grid(HCR~HS) +
  geom_hline(yintercept = 0.2, linetype = "dashed") +
  geom_hline(yintercept = 0.3, linetype = "dashed") +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  ylab("Dynamic SBR") +
  theme_bw()

SBR_d <- Output_MSE %>%
  group_by(HS, HCR, Year) %>%
  mutate(low = quantile(SBR_d, 0.1, na.rm = TRUE),
         medium = mean(SBR_d, na.rm = TRUE),
         high = quantile(SBR_d, 0.9, na.rm = TRUE))

ggplot(data = SBR_d) +
  geom_ribbon(aes(x = Year, ymin = low, ymax = high, fill = HCR), alpha = 0.25) +
  geom_line(aes(x = Year, y = medium, color = HCR), linewidth = 1) +
  geom_hline(yintercept = 0.2, linetype = "dashed") +
  geom_hline(yintercept = 0.3, linetype = "dashed") +
  facet_wrap(~ HS) +
  ylab("Dynamic SBR") +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

SBR_d_OM <- Output_MSE %>%
  group_by(HS, HCR, Year, Model) %>%
  mutate(low = quantile(SBR_d, 0.1, na.rm = TRUE),
         medium = mean(SBR_d, na.rm = TRUE),
         high = quantile(SBR_d, 0.9, na.rm = TRUE))

ggplot(data = SBR_d_OM) +
  geom_ribbon(aes(x = Year, ymin = low, ymax = high, fill = Model), alpha = 0.25) +
  geom_line(aes(x = Year, y = medium, color = Model), linewidth = 1) +
  # geom_hline(yintercept = 0.2) +
  geom_hline(yintercept = 0.2, linetype = "dashed") +
  facet_grid(HCR ~ HS) +
  ylab("Dynamic SBR") +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

SBR_d_q <- Output_MSE %>%
  group_by(HS, HCR, Year, Catchability) %>%
  mutate(low = quantile(SBR_d, 0.1, na.rm = TRUE),
         medium = mean(SBR_d, na.rm = TRUE),
         high = quantile(SBR_d, 0.9, na.rm = TRUE))

ggplot(data = SBR_d_q) +
  geom_ribbon(aes(x = Year, ymin = low, ymax = high, fill = Catchability), alpha = 0.25) +
  geom_line(aes(x = Year, y = medium, color = Catchability), linewidth = 1) +
  # geom_hline(yintercept = 0.2) +
  geom_hline(yintercept = 0.2, linetype = "dashed") +
  facet_grid(HCR ~ HS) +
  ylab("Dynamic SBR") +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

p_SBR_d <- Output_MSE %>%
  mutate(check = SBR_d < 0.2) %>%
  group_by(HS, HCR) %>%
  summarise(p = sum(check)/ n())
kable(p_SBR_d,caption = "p(SBR_d) < 0.2")

ggplot(data = Output_MSE) +
  geom_violin(aes(x = HCR, y = SBR_d, color = HCR), draw_quantiles = c(0.1, 0.5, 0.9)) +
  geom_hline(yintercept = 0.2, linetype = "dashed") +
  facet_wrap(~ HS) +
  theme_bw()
```

```{r SBR}
ggplot(data = Output_MSE) +
  geom_point(aes(x = Year, y = SBR, color = Model), alpha = 0.5, size = 1) +
  facet_grid(HCR~HS) +
  geom_hline(yintercept = 0.077) +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), alpha = 0.25, linetype = "dashed") +
  theme_bw()

SBR <- Output_MSE %>%
  group_by(HS, HCR, Year) %>%
  mutate(low = quantile(SBR, 0.1, na.rm = TRUE),
         medium = mean(SBR, na.rm = TRUE),
         high = quantile(SBR, 0.9, na.rm = TRUE))

ggplot(data = SBR) +
  geom_ribbon(aes(x = Year, ymin = low, ymax = high, fill = HCR), alpha = 0.25) +
  geom_line(aes(x = Year, y = medium, color = HCR), linewidth = 1) +
  geom_hline(yintercept = 0.077, linetype = "dashed") +
  ylab("SBR") +
  facet_wrap(~ HS) +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

SBR_OM <- Output_MSE %>%
  group_by(HS, HCR, Year, Model) %>%
  mutate(low = quantile(SBR, 0.1, na.rm = TRUE),
         medium = mean(SBR, na.rm = TRUE),
         high = quantile(SBR, 0.9, na.rm = TRUE))

ggplot(data = SBR_OM) +
  geom_ribbon(aes(x = Year, ymin = low, ymax = high, fill = Model), alpha = 0.25) +
  geom_line(aes(x = Year, y = medium, color = Model), linewidth = 1) +
  geom_hline(yintercept = 0.077, linetype = "dashed") +
  facet_grid(HCR ~ HS) +
  ylab("SBR") +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

p_SBR <- Output_MSE %>%
  mutate(check = SBR < 0.077) %>%
  group_by(HS, HCR) %>%
  summarise(p = sum(check)/ n())
kable(p_SBR,caption = "p(SBR) < 0.077")

ggplot(data = Output_MSE) +
  geom_violin(aes(x = HCR, y = SBR, color = HCR), draw_quantiles = c(0.1, 0.5, 0.9)) +
  geom_hline(yintercept = 0.077) +
  facet_wrap(~ HS) +
  theme_bw()
```

```{r average catch}
Catch <- Output_MSE %>%
  filter(is.na(Catch) == FALSE) %>%
  group_by(HS, HCR, Model, Catchability, itr, year) %>%
  summarise(Catch_annual = sum(Catch))

Catch_plot <- Catch %>%
  group_by(HS, HCR, year) %>%
  summarise(low = quantile(Catch_annual, 0.1, na.rm = TRUE),
         medium = mean(Catch_annual, na.rm = TRUE),
         high = quantile(Catch_annual, 0.9, na.rm = TRUE))

ggplot(data = Catch_plot) +
  geom_ribbon(aes(x = year, ymin = low, ymax = high, fill = HCR), alpha = 0.25) +
  geom_line(aes(x = year, y = medium, color = HCR), linewidth = 1) +
  ylab("Catch") +
  facet_wrap(~ HS) +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

Catch_plot_Model <- Catch %>%
  group_by(HS, HCR, Model, year) %>%
  summarise(low = quantile(Catch_annual, 0.1, na.rm = TRUE),
         medium = mean(Catch_annual, na.rm = TRUE),
         high = quantile(Catch_annual, 0.9, na.rm = TRUE))

ggplot(data = Catch_plot_Model) +
  geom_ribbon(aes(x = year, ymin = low, ymax = high, fill = Model), alpha = 0.25) +
  geom_line(aes(x = year, y = medium, color = Model), linewidth = 1) +
  ylab("Catch") +
  facet_grid(HCR ~ HS) +
  geom_vline(xintercept = 2025 + seq(Mcycle, nyears - Mcycle, Mcycle), linetype = "dashed") +
  theme_bw()

ggplot(data = Catch) +
  geom_violin(aes(x = HCR, y = Catch_annual, color = HCR), draw_quantiles = c(0.1, 0.5, 0.9)) +
  facet_wrap(~ HS) +
  theme_bw()

Catch_stats <- Catch %>%
  group_by(HS, HCR, year) %>%
  summarise(Catch_HCR = mean(Catch_annual)) %>%
  group_by(HS, HCR) %>%
  summarise(ave_catch = mean(Catch_HCR),
            CV_catch = sd(Catch_HCR)/mean(Catch_HCR))

Catch_pre <- Catch %>% 
  rename(Catch_annual_next = Catch_annual) %>%
  mutate(year = year + 1)

Catch_diff <- left_join(Catch, Catch_pre) %>%
  mutate(abs_diff = abs(Catch_annual - Catch_annual_next)) %>%
  group_by(HS, HCR) %>%
  summarise(AAV = sum(abs_diff, na.rm = TRUE) / sum(Catch_annual_next, na.rm = TRUE))

Catch_stats <- left_join(Catch_stats, Catch_diff)

kable(Catch_stats,caption = "Catch")
```

```{r average closure}
Closure_plot <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Step) %>%
  summarise(low = quantile(closure, 0.1, na.rm = TRUE),
         medium = mean(closure, na.rm = TRUE),
         high = quantile(closure, 0.9, na.rm = TRUE))

ggplot(data = Closure_plot) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR), size = 1) +
  # geom_line(aes(x = Step, y = medium, color = HCR), size = 1) +
  geom_point(aes(x = Step, y = medium, color = HCR), size = 3) +
  facet_wrap(~ HS) +
  ylab("Closure days") +
  xlab("Management cycle") +
  theme_bw()

Closure_plot_Model <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Model, Step) %>%
  summarise(low = quantile(closure, 0.1, na.rm = TRUE),
         medium = mean(closure, na.rm = TRUE),
         high = quantile(closure, 0.9, na.rm = TRUE))

ggplot(data = Closure_plot_Model) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = Model), size = 1) +
  geom_point(aes(x = Step, y = medium, color = Model), size = 3) +
  ylab("Closure days") +
  facet_grid(HCR ~ HS) +
  theme_bw()

ggplot(data = Record_all) +
  geom_violin(aes(x = HCR, y = closure, color = HCR), draw_quantiles = c(0.1, 0.5, 0.9)) +
  facet_wrap(~ HS) +
  theme_bw()
```

```{r change in closure}
Closure_change <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  select(HS, HCR, OM, itr, Step, closure_diff)

Closure_change_plot <- Closure_change %>%
  group_by(HS, HCR, Step) %>%
  summarise(low = quantile(closure_diff, 0.1, na.rm = TRUE),
         medium = mean(closure_diff, na.rm = TRUE),
         high = quantile(closure_diff, 0.9, na.rm = TRUE))

ggplot(data = Closure_change_plot) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR), size = 1) +
  geom_point(aes(x = Step, y = medium, color = HCR), size = 3) +
  ylab("Change in closure days") +
  facet_wrap(~ HS) +
  theme_bw()

ggplot(data = Closure_change) +
  geom_violin(aes(x = HCR, y = closure_diff, color = HCR), draw_quantiles = c(0.1, 0.5, 0.9), scale = "width") +
  facet_wrap(~ HS) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  theme_bw()

Closure_stats <- Closure_change %>%
  group_by(HS, HCR) %>%
  summarise(AAV = mean(closure_diff))
kable(Closure_stats,caption = "Catch")
```

```{r Fratio}
# Fratio_plot <- Record_all %>%
#   mutate(Step = as.numeric(Step)) %>%
#   group_by(HS, HCR, Step) %>%
#   summarise(low = quantile(Fratio, 0.1, na.rm = TRUE),
#          medium = mean(Fratio, na.rm = TRUE),
#          high = quantile(Fratio, 0.9, na.rm = TRUE))
# 
# ggplot(data = Fratio_plot) +
#   geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR), size = 1) +
#   geom_point(aes(x = Step, y = medium, color = HCR), size = 3) +
#   ylab("Fratio") +
#   facet_wrap(~ HS) +
#   theme_bw()
```

```{r F/F30}
F_F30 <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Step) %>%
  summarise(low = quantile(Fcurrent/F30, 0.1, na.rm = TRUE),
         medium = mean(Fcurrent/F30, na.rm = TRUE),
         high = quantile(Fcurrent/F30, 0.9, na.rm = TRUE))

ggplot(data = F_F30) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR), size = 1) +
  geom_point(aes(x = Step, y = medium, color = HCR), size = 3) +
  facet_wrap(~ HS) +
  theme_bw() +
  geom_hline(yintercept = 1) +
  ylab("F / F30%") +
  xlab("Management cycle")

F_F30_EM <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Step) %>%
  summarise(low = quantile(Fcurrent_EM*Fratio/F30_EM, 0.1, na.rm = TRUE),
         medium = mean(Fcurrent_EM*Fratio/F30_EM, na.rm = TRUE),
         high = quantile(Fcurrent_EM*Fratio/F30_EM, 0.9, na.rm = TRUE))

ggplot(data = F_F30_EM) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR), size = 1) +
  geom_point(aes(x = Step, y = medium, color = HCR), size = 3) +
  facet_wrap(~ HS) +
  theme_bw() +
  geom_hline(yintercept = 1) +
  ylab("F / F30%") +
  xlab("Management cycle")

F_F30_Model <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Model, Step) %>%
  summarise(low = quantile(Fcurrent/F30, 0.1, na.rm = TRUE),
         medium = mean(Fcurrent/F30, na.rm = TRUE),
         high = quantile(Fcurrent/F30, 0.9, na.rm = TRUE))

ggplot(data = F_F30_Model) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = Model), size = 1) +
  geom_point(aes(x = Step, y = medium, color = Model), size = 3) +
  facet_grid(HCR ~ HS) +
  theme_bw() +
  geom_hline(yintercept = 1) +
  ylab("F / F30%") +
  xlab("Management cycle")
```

```{r SBR_d EM}
SBR_d_Model <- Record_all %>%
  mutate(Step = as.numeric(Step)) %>%
  group_by(HS, HCR, Model, Step) %>%
  summarise(low = quantile(SBR_d, 0.1, na.rm = TRUE),
         medium = mean(SBR_d, na.rm = TRUE),
         high = quantile(SBR_d, 0.9, na.rm = TRUE))

ggplot(data = SBR_d_Model) +
  geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = Model), size = 1) +
  geom_point(aes(x = Step, y = medium, color = Model), size = 3) +
  facet_grid(HCR ~ HS) +
  theme_bw() +
  geom_hline(yintercept = 0.3, linetype = "dashed") +
  ylab("Dynamic SBR from the EM") +
  xlab("Management cycle")

ggplot(data = Record_all) +
  geom_violin(aes(x = Step, y = SBR_d, color = Model), draw_quantiles = c(0.1, 0.5, 0.9)) +
  theme_bw()
```

```{r FFMSY}
# F_FMSY <- Record_all %>%
#   mutate(Step = as.numeric(Step)) %>%
#   group_by(HS, HCR, Step) %>%
#   summarise(low = quantile(FFMSY, 0.1, na.rm = TRUE),
#          medium = mean(FFMSY, na.rm = TRUE),
#          high = quantile(FFMSY, 0.9, na.rm = TRUE))
# 
# ggplot(data = F_FMSY) +
#   # geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR)) +
#   geom_line(aes(x = Step, y = medium, color = HCR), size = 1) +
#   facet_wrap(~ HS) +
#   theme_bw() +
#   geom_hline(yintercept = 1) +
#   ylab("F / FMSY") +
#   xlab("Management cycle")

# F_F30_OM <- Record_all %>%
#   mutate(Step = as.numeric(Step)) %>%
#   group_by(HS, HCR, OM, Step) %>%
#   summarise(low = quantile(Fcurrent/F30, 0.1, na.rm = TRUE),
#          medium = mean(Fcurrent/F30, na.rm = TRUE),
#          high = quantile(Fcurrent/F30, 0.9, na.rm = TRUE))
# 
# ggplot(data = F_F30_OM) +
#   # geom_errorbar(aes(x = Step, ymin = low, ymax = high, color = HCR)) +
#   geom_line(aes(x = Step, y = medium, color = OM),size=1) +
#   facet_grid(HCR ~ HS) +
#   theme_bw() +
#   geom_hline(yintercept = 1) +
#   ylab("F / F30%") +
#   xlab("Management cycle")
```

```{r trade-off}
Catch <- Output_MSE %>%
  filter(is.na(Catch) == FALSE) %>%
  group_by(HS, HCR, Model, Catchability, itr, year) %>%
  summarise(Catch_annual = sum(Catch)) %>%
  group_by(HS, HCR) %>%
  summarise(ave_catch = mean(Catch_annual))

dSBR <- Output_MSE %>%
  group_by(HS, HCR) %>%
  summarise(ave_dSBR = mean(SBR_d))

Closure <- Record_all %>%
  group_by(HS, HCR) %>%
  summarise(ave_closure = mean(closure, na.rm = TRUE))

Tradeoff <- data.frame("HS" = Catch$HS, "HCR" = Catch$HCR, "Catch" = Catch$ave_catch, "Closure" = Closure$ave_closure, "dSBR" = dSBR$ave_dSBR)

ggplot(data = Tradeoff) +
  geom_point(aes(x = Closure, y = dSBR, color = HS, size = Catch)) +
  theme_bw() +
  coord_cartesian(xlim = c(0, 20), ylim = c(0, 0.4), expand = FALSE)
```