---
title: "MSE_analysis"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initial_setup}

library(tidyr)
library(dplyr)
library(ggplot2)

# Specify path of parent directory
pdir = "D:/OneDrive - IATTC/IATTC/2025/MSE/Test/"

# Specify the path of conditioned initial OM
sdir = "D:/OneDrive - IATTC/IATTC/2025/SAC16/BET F30/"

# Dimensions
library(IATTCMSE)
library(foreach)
library(doParallel)

#Specify path of parent directory
pdir <- "D:/OneDrive - IATTC/IATTC/2025/MSE/Test/"

#Specify the path of conditioned initial OM
sdir <- "D:/OneDrive - IATTC/IATTC/2025/SAC16/BET F30/"

# Dimensions
niterations <- 3
nyears <- 9
nquarters <- nyears * 4
Mcycle <- 3
nsteps <- nyears / Mcycle
endquarter <- 196
startquarter <- 17
n_extra_R <- 2 #number of assessment period recruitment in the projection
EM_comp_fleet <- c(4, 23) # fleets with comps in ASPM Rdevs+

OM_name <- c("Fix-1-1", "Sel-1-1", "Gro-1-1", "Mrt-1-1")
HCR_name <- c("HCR_staff", "HCR_staff_0")

# Set the harvest strategy
HSnum <- 1
HS <- paste0("HS", HSnum, "/")

# Set the HCR
HCRnum <- 1
HCR <- paste0(HCR_name[HCRnum], "/")
```

```{r management_output}
for (OMnum in 1:4) {
  # Set the scenario
  OM <- paste0(OM_name[OMnum], "/")
  
  # extract saved management output
  for (itrnum in 1:niterations) {
    itr = paste0("itr", itrnum, "/")
    Record <- read.csv(paste0(paste0(pdir, HS, HCR, OM, itr, "Record.csv")))
    Record$Step <- 1:nsteps
    Record$OM <- OM
    Record$itr <- itrnum
    
    if (OMnum == 1 & itrnum == 1)
      Record_all <- Record
    else
      Record_all <- rbind(Record_all, Record)
  }
  
  Record_all$itr <- as.factor(Record_all$itr)
}

Record_all$Step <- as.factor(Record_all$Step)

ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = closure, fill = OM)) +
  theme_bw()
  
# gggeom_violin()ggplot(data = Record_all) +
#   geom_line(aes(x = Step, y = SBR_d, color = itr)) +
#   geom_point(aes(x = Step, y = SBR_d, color = itr)) +
#   theme_bw()
# 
ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = Fadjust, fill = OM)) +
  theme_bw() +
  ylab("F/F30%")

ggplot(data = Record_all) +
  geom_boxplot(aes(x = Step, y = (Time_Stamp - min(Time_Stamp))/60, fill = OM)) +
  theme_bw() +
  ylab("Time chart in minute")
```

```{r fig.height=15, fig.width=10}
for (OMnum in 1:4) {
  # Set the scenario
  OM <- paste0(OM_name[OMnum], "/")
  
  for (itrnum in 1:niterations) {
    itr = paste0("itr", itrnum, "/")
    Output <- read.csv(paste0(paste0(pdir, HS, HCR, OM, itr, "Output.csv")))
    Output$OM <- OM
    Output$itr <- itrnum
    
    if (OMnum == 1 & itrnum == 1)
      Output_all <- Output
    else
      Output_all <- rbind(Output_all, Output)
  }
}

Output_all_long <- Output_all %>%
  mutate(itr = as.factor(itr),
         Year = Year / 4 + 1974.875,
         year = floor(Year) + 0.5) %>%
  gather(2:7, key = "Quantity", value = "Value") %>%
  filter(Quantity %in% c("Catch", "SB", "SBR", "SBR_d", "Recruit"))

output_all_old <- Output_all_long %>%
  filter(Year < 2024)
output_all_new <- Output_all_long %>%
  filter(Year > 2024, Year < max(Year))

ggplot() +
  geom_point(aes(x = Year, y = Value, color = OM, shape = OM), alpha = 1, data = output_all_new) +
  geom_vline(xintercept = c(seq(0, nyears, Mcycle) + 2024), linetype = "dashed") +
  facet_wrap(~Quantity, scales = "free_y", nrow = 5) +
  theme_bw()

ggplot() +
  geom_boxplot(aes(x = factor(year), y = Value, fill = OM), data = output_all_new) +
  geom_vline(xintercept = factor(c(seq(0, nyears, Mcycle) + 2024)), linetype = "dashed") +
  facet_wrap(~Quantity, scales = "free_y", nrow = 5) +
  theme_bw()
```
